/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TriggerMsg'
 * message type.
 */

public class TriggerMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 12;

    /** Create a new TriggerMsg of size 2. */
    public TriggerMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TriggerMsg of the given data_length. */
    public TriggerMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TriggerMsg with the given data_length
     * and base offset.
     */
    public TriggerMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TriggerMsg using the given byte array
     * as backing store.
     */
    public TriggerMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TriggerMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TriggerMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TriggerMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TriggerMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TriggerMsg embedded in the given message
     * at the given base offset.
     */
    public TriggerMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TriggerMsg embedded in the given message
     * at the given base offset and length.
     */
    public TriggerMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TriggerMsg> \n";
      try {
        s += "  [sendingnode=0x"+Long.toHexString(get_sendingnode())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sendingnode
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sendingnode' is signed (false).
     */
    public static boolean isSigned_sendingnode() {
        return false;
    }

    /**
     * Return whether the field 'sendingnode' is an array (false).
     */
    public static boolean isArray_sendingnode() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sendingnode'
     */
    public static int offset_sendingnode() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sendingnode'
     */
    public static int offsetBits_sendingnode() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'sendingnode'
     */
    public int get_sendingnode() {
        return (int)getUIntBEElement(offsetBits_sendingnode(), 16);
    }

    /**
     * Set the value of the field 'sendingnode'
     */
    public void set_sendingnode(int value) {
        setUIntBEElement(offsetBits_sendingnode(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sendingnode'
     */
    public static int size_sendingnode() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sendingnode'
     */
    public static int sizeBits_sendingnode() {
        return 16;
    }

}
